/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.vhabitacion;
import Files.fhabitacion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Silvia
 */
public class frmHabitacion extends javax.swing.JInternalFrame{

    /**
     * Creates new form frmHabitacion
     */
    public frmHabitacion() {
        initComponents();
        mostrar("");
        inhabilitar();
        
    }
    private String accion="guardar";
    
    void ocultar_columnas(){
    tablalistado.getColumnModel().getColumn(0).setMaxWidth(0);
    tablalistado.getColumnModel().getColumn(0).setMinWidth(0);
    tablalistado.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
     void inhabilitar (){
        txtidhabitacion.setVisible(false);
       cbopiso2.setEnabled(false);
       txtnumero.setEnabled(false);
       txtdescripcion.setEnabled(false);
       txtcaracteristicas.setEnabled(false);
       txtpreciodiario.setEnabled(false);
       cboestado.setEnabled(false);
       cbotipohabitacion.setEnabled(false);
    btnguardar.setEnabled(false);
    btncancelar.setEnabled(false);
    btnnuevo.setEnabled(true);
    txtidhabitacion.setText("");
    txtcaracteristicas.setText("");
    txtpreciodiario.setText("");
    txtdescripcion.setText("");
    
    
    }
    
    void habilitar (){
    txtidhabitacion.setVisible(false);
       cbopiso2.setEnabled(true);
       txtnumero.setEnabled(true);
       txtdescripcion.setEnabled(true);
       txtcaracteristicas.setEnabled(true);
       txtpreciodiario.setEnabled(true);
       cboestado.setEnabled(true);
       cbotipohabitacion.setEnabled(true);
    btnguardar.setEnabled(true);
    btnnuevo.setEnabled(true);
    btncancelar.setEnabled(true);
    txtidhabitacion.setText("");
    txtcaracteristicas.setText("");
    txtpreciodiario.setText("");
    txtdescripcion.setText("");
    }
    
    void mostrar (String buscar){
    try{
        DefaultTableModel modelo;
        fhabitacion func = new fhabitacion();
        modelo = func.mostrar(buscar); //le envio el parametro de buscar
        tablalistado.setModel(modelo); //le envio lo q obtengo como modelo
        ocultar_columnas();
        lbltotalregistros.setText("Total registros "+ Integer.toString(func.totalregistros));  //como instancie el objeto fhabitacion, puedo llamar a la var total registros declarda en ese obj
    }catch(Exception e){
        JOptionPane.showConfirmDialog(rootPane, e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel2 = new javax.swing.JLabel();
        txtidhabitacion = new javax.swing.JTextField();
        txtpreciodiario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbotipohabitacion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcaracteristicas = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        cboestado = new javax.swing.JComboBox<>();
        cbopiso2 = new javax.swing.JComboBox<>();
        btnguardar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        btncancelar = new javax.swing.JButton();
        panel2 = new org.edisoncor.gui.panel.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablalistado = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        lbltotalregistros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("jLabel1");

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Habitaciones"));
        panel1.setColorPrimario(new java.awt.Color(153, 153, 255));
        panel1.setColorSecundario(new java.awt.Color(153, 153, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Numero:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        panel1.add(txtidhabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 16, 166, -1));

        txtpreciodiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreciodiarioActionPerformed(evt);
            }
        });
        panel1.add(txtpreciodiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 166, -1));

        jLabel3.setText("Piso:");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        cbotipohabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));
        cbotipohabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotipohabitacionActionPerformed(evt);
            }
        });
        panel1.add(cbotipohabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 166, -1));

        txtcaracteristicas.setColumns(20);
        txtcaracteristicas.setRows(5);
        jScrollPane1.setViewportView(txtcaracteristicas);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, 54));

        jLabel5.setText("Caracteristicas:");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setText("Precio Diario");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 87, -1));

        jLabel7.setText("Estado:");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel8.setText("Tipo de Hab: ");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        txtdescripcion.setColumns(20);
        txtdescripcion.setRows(5);
        jScrollPane3.setViewportView(txtdescripcion);

        panel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 129, -1, 54));

        cboestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));
        cboestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboestadoActionPerformed(evt);
            }
        });
        panel1.add(cboestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 166, -1));

        cbopiso2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));
        cbopiso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbopiso2ActionPerformed(evt);
            }
        });
        panel1.add(cbopiso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 98, 166, -1));

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        panel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        panel1.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel9.setText("Descripcion:");
        panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroActionPerformed(evt);
            }
        });
        panel1.add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 54, 166, -1));

        btncancelar.setText("Cancelar");
        panel1.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        panel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Habitaciones"));
        panel2.setColorPrimario(new java.awt.Color(102, 255, 153));

        tablalistado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablalistado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablalistadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablalistado);

        jLabel4.setText("Buscar");

        jButton1.setText("Buscar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        lbltotalregistros.setText("REGISTROS");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btneliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6)))
                        .addGap(18, 18, 18))))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btneliminar)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
             if(!txtidhabitacion.getText().equals("")){
                 //
           int confirmacion=JOptionPane.showConfirmDialog(rootPane, "Estas seguro de eliminar la Habitacion?","Confirmar",2);
       if(confirmacion==0){
           fhabitacion func = new fhabitacion();
           vhabitacion dts = new vhabitacion();
           
           dts.setIdHabitacion(Integer.parseInt(txtidhabitacion.getText()));
           func.eliminar(dts);
           mostrar("");
           inhabilitar();
       
       }
       
       }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
  habilitar();
       btnguardar.setText("Guardar");
       accion="guardar";
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
                                                   
        if(txtnumero.getText().length()==0){ //si obtengo el texto, calcylo el largo con lenght y es iwual a 0
        JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un numero de Habitacion");
        txtnumero.requestFocus();
        return;
        }
         if(txtdescripcion.getText().length()==0){
        JOptionPane.showConfirmDialog(rootPane, "Debes ingresar la descripcion");
        txtdescripcion.requestFocus();
        return;
        }
          if(txtpreciodiario.getText().length()==0){
        JOptionPane.showConfirmDialog(rootPane, "Debes ingresar el precio diario de Habitacion");
        txtpreciodiario.requestFocus();
        return;
        }
           if(txtcaracteristicas.getText().length()==0){
        JOptionPane.showConfirmDialog(rootPane, "Debes ingresar Caracteristica de la Habitacion");
        txtcaracteristicas.requestFocus();
        return;
        }
           
           vhabitacion dts = new vhabitacion();
    fhabitacion func = new fhabitacion();  
    
    dts.setNumero(txtnumero.getText());
    //primero hay q seleccionar el indice pa desp enviarlo,primero se declarda una var
    int seleccionado=cbopiso2.getSelectedIndex();
    dts.setPiso((String)cbopiso2.getItemAt(seleccionado));
    
    dts.setDescripcion(txtdescripcion.getText());
    dts.setCaracteristicas(txtcaracteristicas.getText());
    dts.setPrecio_diario(Double.parseDouble(txtpreciodiario.getText()));
    
     seleccionado=cboestado.getSelectedIndex();
    dts.setEstado((String)cboestado.getItemAt(seleccionado));
    seleccionado=cbotipohabitacion.getSelectedIndex();
dts.setTipo_habitacion((String)cbotipohabitacion.getItemAt(seleccionado));

if(accion.equals("guardar")){ //si mi accion q declare al ppio e igual a guradar
        if(func.insertar(dts)){ // para ver si puedo o no almacenar registros en la tabla
        JOptionPane.showMessageDialog(rootPane, "Habitacion registrada satisfoctoriamente");
            mostrar(""); //cadena vacia pa q muestre todos los registros
        inhabilitar();
        }
        
    }else if (accion.equals("editar")){
    dts.setIdHabitacion(Integer.parseInt(txtidhabitacion.getText()));
    if(func.editar(dts)){
    JOptionPane.showMessageDialog(rootPane, "Habitacion editada satisfoctoriamente");
            mostrar("");
            inhabilitar();
    }
    }


    }//GEN-LAST:event_btnguardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mostrar(txtbuscar.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroActionPerformed
txtnumero.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroActionPerformed

    private void cbopiso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbopiso2ActionPerformed
cbopiso2.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_cbopiso2ActionPerformed

    private void txtpreciodiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreciodiarioActionPerformed
       txtpreciodiario.transferFocus();
    }//GEN-LAST:event_txtpreciodiarioActionPerformed

    private void cboestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboestadoActionPerformed
cboestado.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_cboestadoActionPerformed

    private void cbotipohabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotipohabitacionActionPerformed
        cbotipohabitacion.transferFocus();
    }//GEN-LAST:event_cbotipohabitacionActionPerformed

    private void tablalistadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablalistadoMouseClicked
        btnguardar.setText("Editar"); //cuando click en un registro  my btnguardar va a decir ediar
        habilitar();
        btneliminar.setEnabled(true);
        accion="editar"; //mi var accion sera editar
        
        int fila=tablalistado.rowAtPoint(evt.getPoint());
        
        //capturar los datos pa poder enviarlos a mi caja d texto
        txtidhabitacion.setText(tablalistado.getValueAt(fila, 0).toString());
        txtnumero.setText(tablalistado.getValueAt(fila, 1).toString());
        
        cbopiso2.setSelectedItem(tablalistado.getValueAt(fila, 2).toString());
        txtdescripcion.setText(tablalistado.getValueAt(fila, 3).toString());
        txtcaracteristicas.setText(tablalistado.getValueAt(fila, 4).toString());
        txtpreciodiario.setText(tablalistado.getValueAt(fila, 5).toString());
        
        cboestado.setSelectedItem(tablalistado.getValueAt(fila, 6).toString());
        cbotipohabitacion.setSelectedItem(tablalistado.getValueAt(fila, 7).toString());
    }//GEN-LAST:event_tablalistadoMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

      
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHabitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox<String> cboestado;
    private javax.swing.JComboBox<String> cbopiso2;
    private javax.swing.JComboBox<String> cbotipohabitacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbltotalregistros;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private javax.swing.JTable tablalistado;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextArea txtcaracteristicas;
    private javax.swing.JTextArea txtdescripcion;
    private javax.swing.JTextField txtidhabitacion;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtpreciodiario;
    // End of variables declaration//GEN-END:variables
}
